### ISSUE TITLE
label.textWrap only wraps to a second line

### ISSUE THREAD

**Issue by msywensky** [NativeScript/cross-platform-modules#262] opened 2015-04-05 03:44 UTC
If label.textWrap = true and the text is longer than two lines, the ellipsis shows on the 2nd line.  I would expect a 3rd line to be displayed.

**Comment by hamorphis** [comment] 2015-04-06 08:52
I will try to reproduce this behavior on both platforms.

**Comment by hamorphis** [comment] 2015-04-06 09:41
Unfortunately I cannot reproduce this.

Can you please post some sample XML with a Label that will reproduce this behavior. Here is what I am currently testing with:

```xml
<Page>
    <Label id="label" 
           textWrap="true"
           text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a orci quis nulla vestibulum auctor at eu erat." 
           width="100" 
           height="100"
           backgroundColor="PaleGreen"/>
</Page>
```

And here is what I see in iOS.
![ios simulator screen shot apr 6 2015 12 33 58 pm](https://cloud.githubusercontent.com/assets/1201857/7002808/4812b1e6-dc59-11e4-8575-d525d1d7c379.png)

And in Android:
![android](https://cloud.githubusercontent.com/assets/1201857/7002833/adc21f54-dc59-11e4-9cb1-46d5c62a710c.png)

By the way, here is what really happens when you set textWrap to true in iOS:

```JavaScript
label.ios.lineBreakMode = NSLineBreakMode.NSLineBreakByWordWrapping;
label.ios.numberOfLines = 0;
```

And here is what we do in Android:

```JavaScript
label.android.setSingleLine(false);
label.android.setEllipsize(null);
```

We simply set those properties of the native controls. We don't do anything special or additional.

**Comment by msywensky** [comment] 2015-04-06 13:21
Sorry, I stated the bug incorrectly.  An ellipse does not show, but the entire string is not displayed.

```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout style="padding:30">
    <Label style="font-size:18;text-align:center;" textWrap="true"
				text="Search by place-name, postcode or search near your location" />
   </StackLayout>
</Page>
```
The word "location" is not being displayed on iOS.

![screen shot 2015-04-06 at 9 20 22 am](https://cloud.githubusercontent.com/assets/5222771/7004765/3ecdb4e8-dc3e-11e4-929e-0135fd3e288c.png)

**Comment by hamorphis** [comment] 2015-04-08 08:07
Have you tried setting the height of the Label? If you set some background color, you will see the label boundaries. I assume that it is just not high enough to display the entire string.

**Comment by hamorphis** [comment] 2015-04-14 06:57
I guess I can close this issue.

**Closed by hamorphis** 2015-04-14 06:57 UTC
Labels: 3 - In Progress, S:Medium, T:Bug

**Comment by msywensky** [comment] 2015-04-15 02:55
Sorry for not replying sooner.  I would expect the field to grow in size without requiring setting the height.  For other strings it works without setting the height.  Something is wrong here.

```xml
<Page xmlns="http://www.nativescript.org/tns.xsd" >
	<StackLayout style="padding:30">

		<Label  style="background-color:yellow;font-size:18" textWrap="true"
                text="Search by place-name, postcode or search near your location more stuff" />

		<Label  style="background-color:green;font-size:18" textWrap="true"
                text="Now is the time for all good men to come to the aid of their party.  The quick brown fox jumped over the lazy dog." />
	</StackLayout>
</Page>
```

![screen shot 2015-04-14 at 10 54 58 pm](https://cloud.githubusercontent.com/assets/5222771/7151524/585dcd46-e2f9-11e4-8b62-5c8a33e29cd7.png)

**Comment by tcak** [comment] 2016-10-13 13:47
I am having the similar problem on iOS while there is no problem on Android. Xcode 8, iOS 10 is used. textWrap is set true, and the text has a background colour so I can see where it ends. The last word of text is a little long and doesn't fit to the last line, so it should be seen in the next line. But there is no new line. As I understand, height is calculated wrong.

**Comment by NordlingArt** [comment] 2016-10-20 12:19
@tcak - I can also confirm this. Last word is "Aventador", but shows as:

![image](https://cloud.githubusercontent.com/assets/2098838/19559417/0b119aa4-96d0-11e6-9248-e6c1b4988134.png)

**Platform:** iOS 9.3 (Simulator)
**TNS:** 2.3.0
